<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lesson 60. Javascript </title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
<h1>Содержимое страницы</h1>

<form id="form" name="form" action="/demo/post" method="post">
    <input type="text" placeholder="Логин" name="login">
    <input type="password" placeholder="Пароль" name="password">
    <button type="submit">Войти</button>
</form>
</body>
</html>

<script src="/js/script.js"></script>
